### List all messages
GET http://localhost:3000/messages

### Create a new message
POST  http://localhost:3000/messages
content-type: application/json

{
    "content": "Kceriderf"
}

### Find message by Id
GET  http://localhost:3000/messages/113